### ISSUE TITLE
Cannot run MainApp due to NullPointerException

### ISSUE THREAD

**Issue by jamesyaputra** [CS2113-AY1819S1-T12-1/main#32]
As of now, we are able to build the .jar file for our application but we cannot run MainApp class directly from IntelliJ.

After looking through the fallback message for the `NullPointerException`, it can be concluded that there is a problem with the program reading the `FXML` file named `MainWindow.fxml` in the `resources/view/` folder.

Could @chiaxr @Geraldcdx @cqinkai @Tertium3 look into this as well?

**Comment by cqinkai** [comment]
why is this tagged as user story type lol

**Comment by jamesyaputra** [comment]
@cqinkai My bad lol
